folder_name='SPL Files'
ocr_folder='OCR-Output'
# ocr_filename=input_img_filename.split('.')[0]+'.json'
prompt_json_folder='Prompts'
prompt_json_filename='prompt.json'
spl_key='SPL_Key.csv'
spl_key_folder='Spl-key'