FROM python:3.9
WORKDIR /code
ENV PORT 8000
EXPOSE 8000
COPY ./* /code/
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN chmod +x ./startup_script.sh
CMD ["./startup_script.sh"]

