steps:
- script: |
   az login --service-principal -u 457a2087-c8e9-4998-9ab6-fcecddada55d -p aKF8Q~h1eSmRhuOpdubRaOzaQk5J4TX2XEIaDcvf --tenant 1f4beacd-b7aa-49b2-aaa1-b8525cb257e0
   cd makesure/FDB-storage-app
   az acr build --image scimg:v$(Build.BuildId) --registry demoin --file dockerfile .
   az extension add --name containerapp --upgrade
   az provider register --namespace Microsoft.App
   az provider register --namespace Microsoft.OperationalInsights
   az containerapp update --name prajwalapp --resource-group myResourceGroup --image demoin.azurecr.io/scimg:v$(Build.BuildId)   
  displayName: 'Build and Deploy'